# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f53d6d01bcb969099ad3514c04b3e40ca497897b324d09df888d2e34b329f19522878a767b3ca1a85ce0e100b52a5ab28451e957dbcb2c7d1b498020542c4437

test:
  secret_key_base: f29905a0172aaf985cd7a71711c837143b24d42da3b10ee53d4c490b5ece887f4033f0410bbae2a3b5a1fa14c93b8fcef31bbc8ac5ce797e7be230359c81af95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
